import Foundation

public extension Recommendation {
    /// A compact, copy-friendly text rendering of a single direction card,
    /// designed for ShareLink / pasteboard / iMessage. Lays out the
    /// shoot-relevant beats in roughly the order a director would call them
    /// out on set: cinema reference → emotional intent → blocking → on-set
    /// camera + light. Trailing FilmPost attribution closes the share.
    var shareText: String {
        var lines: [String] = []
        lines.append("FilmPost direction: \(style)")
        lines.append("Inspired by \(cinemaReference.filmTitle) (\(cinemaReference.director))")
        lines.append("")
        lines.append("DIRECTOR'S NOTE")
        lines.append(directorNote)
        lines.append("")
        lines.append("EMOTIONAL GOAL")
        lines.append(emotionalGoal)
        lines.append("")
        lines.append("POSE")
        lines.append(pose)
        lines.append("")
        lines.append("COMPOSITION")
        lines.append(composition)
        lines.append("")
        lines.append("ON SET")
        lines.append("• Camera: \(cameraDistance)")
        lines.append("• Light: \(lightingTip)")
        lines.append("• Color: \(colorDirection)")
        lines.append("")
        lines.append("WHY THIS REFERENCE")
        lines.append(cinemaReference.whyItConnects)
        lines.append("")
        lines.append("Borrowed technique: \(cinemaReference.borrowedTechnique)")
        lines.append("")
        lines.append("— Generated by FilmPost")
        return lines.joined(separator: "\n")
    }
}
