import Foundation
import Testing
@testable import FilmPostCore


@Test("Recommendation share text includes the cinema anchor and on-set beats")
func recommendationShareTextIncludesAnchorAndBeats() {
    let recommendation = Recommendation(
        style: "Late Train Stillness",
        whyThisMatches: "Tunnel geometry supports a quiet observational portrait.",
        directorNote: "Hold the body still and let the eyes drift.",
        emotionalGoal: "Lonely calm with private interiority.",
        pose: "One shoulder against tile wall.",
        composition: "Negative space toward tracks.",
        colorDirection: "Steel blue, pale amber.",
        cameraDistance: "1.5 m, medium close.",
        lightingTip: "Overhead spill, soft on brow.",
        referenceFilmMood: "Lonely metropolitan calm.",
        cinemaReference: CinemaReference(
            filmTitle: "Lost in Translation",
            director: "Sofia Coppola",
            sceneAnchor: "Hotel-window stillness before the city wakes.",
            whyItConnects: "Cool transit light creates suspended urban solitude.",
            borrowedTechnique: "Let negative space and a softened gaze carry the mood."
        )
    )

    let text = recommendation.shareText

    // The cinema anchor (film + director) is the headline value of the share.
    #expect(text.contains("Lost in Translation"))
    #expect(text.contains("Sofia Coppola"))
    // On-set beats need to make it through; without them the share is just
    // a marketing blurb instead of an actionable shoot brief.
    #expect(text.contains("1.5 m, medium close."))
    #expect(text.contains("Overhead spill, soft on brow."))
    #expect(text.contains("Steel blue, pale amber."))
    // Trailing attribution closes the share so a downstream reader knows
    // where this came from.
    #expect(text.contains("Generated by FilmPost"))
}
